apiVersion: v1
kind: Secret
metadata:
  name: marketflow-db-secret
  namespace: marketflow
type: Opaque
stringData:
  POSTGRES_DB: marketflow
  POSTGRES_USER: marketflow
  POSTGRES_PASSWORD: marketflowpass
  DATABASE_HOST: marketflow-db.marketflow.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_NAME: marketflow
  DATABASE_USER: marketflow
  DATABASE_PASSWORD: marketflowpass
  DATABASE_SSLMODE: disable
---
apiVersion: v1
kind: Service
metadata:
  name: marketflow-db
  namespace: marketflow
  labels:
    app: marketflow-db
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app: marketflow-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: marketflow-db
  namespace: marketflow
  labels:
    app: marketflow-db
spec:
  serviceName: marketflow-db
  replicas: 1
  selector:
    matchLabels:
      app: marketflow-db
  template:
    metadata:
      labels:
        app: marketflow-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-03
      containers:
        - name: timescaledb
          image: 192.168.55.148:5000/mirror/docker.io/timescale/timescaledb:latest-pg16
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: marketflow-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: marketflow-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketflow-db-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: init-sql
          configMap:
            name: marketflow-db-init
        - name: data
          hostPath:
            path: /var/lib/marketflow/timescaledb
            type: DirectoryOrCreate
