apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: apps
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/part-of: dbserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/part-of: dbserver
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
